plugins {
    id 'java-library'
    id 'maven-publish'
    id 'org.cyclonedx.bom' version '3.1.0'
    id 'org.sonarqube' version '4.0.0.2929'
    id 'io.github.sgtsilvio.gradle.javadoc-links' version '0.9.0'
    id 'biz.aQute.bnd.builder' version '7.0.0'
}

sonarqube {
  properties {
    property "sonar.projectKey", "pjfanning_excel-streaming-reader"
    property "sonar.organization", "pjfanning"
    property "sonar.host.url", "https://sonarcloud.io"
    // the plugin seems to not detect our non-standard build-layout
    property "sonar.junit.reportPaths", "$projectDir/build/test-results/test"
  }
}

group = 'com.github.pjfanning'
version = '5.2.0'

sourceCompatibility = 1.8

java {
    withJavadocJar()
    withSourcesJar()
    registerFeature('poiSharedStrings') {
        usingSourceSet(sourceSets.main)
    }
}

repositories {
    mavenCentral()
    // maven { url "https://repository.apache.org/content/groups/staging/" }
}

ext {
    poiVersion = '5.5.1'
    poiSharedStringsVersion = '2.10.0'
    slf4jVersion = '2.0.17'
}

dependencies {
    api "org.apache.poi:poi:$poiVersion"
    api "org.apache.poi:poi-ooxml:$poiVersion"
    api "org.apache.poi:poi-ooxml-full:$poiVersion"
    implementation "org.slf4j:slf4j-api:$slf4jVersion"
    implementation 'commons-io:commons-io:2.21.0'
    implementation 'org.apache.commons:commons-compress:1.28.0'
    poiSharedStringsImplementation "com.github.pjfanning:poi-shared-strings:$poiSharedStringsVersion"
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.nanohttpd:nanohttpd:2.3.1'
    testImplementation 'org.mockito:mockito-core:4.11.0'
    testRuntimeOnly "org.slf4j:slf4j-simple:$slf4jVersion"
    testRuntimeOnly 'org.apache.logging.log4j:log4j-to-slf4j:2.25.2'
}

test {
    options {
        systemProperties(System.getProperties())
    }
}

tasks.named('jar') {
    manifest {
        attributes(
            'Automatic-Module-Name': 'com.github.pjfanning.excelstreamingreader',
            'Bundle-SymbolicName': "${project.group}.${project.name}",
            'Bundle-Name': project.name,
            'Bundle-Version': project.version.toString(),
            'Bundle-ManifestVersion': '2',
            'Export-Package': '' +
                'com.github.pjfanning.xlsx;version=${project.version};-noimport:=true,' +
                'com.github.pjfanning.xlsx.exceptions;version=${project.version};-noimport:=true',
            'Private-Package': '' +
                'com.github.pjfanning.xlsx.impl,' +
                'com.github.pjfanning.xlsx.impl.ooxml',
            'Import-Package': '' +
                '!com.github.pjfanning.xlsx.*,' +
                'com.github.pjfanning.poi.xssf.streaming;resolution:=optional,' +
                '*',
            '-noextraheaders': 'true'
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

compileTestJava.dependsOn('copyLicenseToBuildResources')
jar.dependsOn('copyLicenseToBuildResources')
javadoc.dependsOn('copyLicenseToBuildResources')

publish.dependsOn cyclonedxBom

publishing {
    publications {
        mavenJava(MavenPublication) {
            from(components.java)
            pom {
                name = 'excel-streaming-reader'
                description = 'Streaming Excel reader'
                url = 'https://github.com/webratio/excel-streaming-reader'
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'monitorjbl'
                        name = 'Taylor Jones'
                        email = 'monitorjbl@gmail.com'
                    }
                    developer {
                        id = 'pjfanning'
                        name = 'PJ Fanning'
                        url = 'https://github.com/pjfanning'
                    }
                    developer {
                        id = 'webratio'
                        name = 'WebRatio'
                        url = 'https://www.webratio.com'
                    }
                }
                scm {
                    url = 'https://github.com/webratio/excel-streaming-reader'
                    connection = 'scm:git://github.com/webratio/excel-streaming-reader.git'
                    developerConnection = 'scm:git://github.com/webratio/excel-streaming-reader.git'
                }
            }
        }
    }
}

tasks.register('copyLicenseToBuildResources', Copy) {
    from layout.projectDirectory.file("LICENSE")
    into layout.buildDirectory.dir("resources/main/META-INF")
}

tasks.register('prepareForPublication') {
    group = 'build'
    description = 'Prepare for manual publishing. This task will assemble the project and generate the POM file for the Maven publication.'
    dependsOn 'assemble', 'generatePomFileForMavenJavaPublication'
}
